import json
from itertools import combinations
from collections import Counter


def generate_edges():
    # 1. Loading data generated by extract_games.py
    try:
        with open("players_per_match.json", "r", encoding="utf-8") as f:
            matches = json.load(f)
        with open("player_names.json", "r", encoding="utf-8") as f:
            names = json.load(f)
    except FileNotFoundError:
        print("Error: No JSON files. Run extract_games.py first!")
        return

    # 2. Counting pairs of players (graph edges)
    edges_counter = Counter()

    print("Processing matches and creating connections between players...")
    for players in matches.values():
        # Mapping to names and removing spaces (GraphStream requirement for OD nodes)
        player_names = [names.get(str(p), str(p)).replace(" ", "_") for p in players]

        # Creating unique pairs of players who appeared in the same match
        for p1, p2 in combinations(sorted(player_names), 2):
            edges_counter[(p1, p2)] += 1

    # 3. Writing to a text file for Java
    # Format: Player 1 Player 2 Weight
    output_file = "graph_data.txt"
    with open(output_file, "w", encoding="utf-8") as f:
        for (p1, p2), weight in edges_counter.items():
            f.write(f"{p1} {p2} {weight}\n")

    print(f"Success! File '{output_file}' has been created.")
    print(f"Number of unique edges: {len(edges_counter)}")


if __name__ == "__main__":
    generate_edges()